FROM apache/airflow:3.0.0

COPY ./airflow/requirements.txt /requirements.txt
COPY ./dbt /opt/airflow/dbt

USER root
RUN mkdir -p /opt/airflow/dbt/data_layer_project/logs && \
    chown -R airflow:root /opt/airflow/dbt && \
    chmod -R 775 /opt/airflow/dbt

USER airflow
RUN pip install --no-cache-dir -r /requirements.txt
