# Dockerfile.dbt
FROM python:3.11-slim

# System dependencies
RUN apt-get update && apt-get install -y \
    git \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir dbt-postgres

# Workdir
WORKDIR /app/dbt

# Keep container running (for debugging)
CMD ["tail", "-f", "/dev/null"]
